web/router.ex
defmodule Pong.Router do
  use Pong.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :auth do
    plug Pong.Plugs.Authenticate
    plug Pong.Plugs.UserToken
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Pong do
    pipe_through :browser # Use the default browser stack

    get "/", GameController, :index

    get "/spectate/:id", GameController, :spectate

    resources "sessions", SessionController, only: [ :new, :create ], singleton: true
    get "logout", SessionController, :delete

    get "/account/signup", UserController, :new
    post "/account", UserController, :create
  end

  scope "/", Pong do
    pipe_through :browser
    pipe_through :auth

    resources "games", GameController, only: [:index, :new, :create]
    get "/games/:id/play", GameController, :play
    get "/games/:id/control", GameController, :control
    get "/games/:id/:mode", GameController, :show

    put "/account", UserController, :update
    delete "/account", UserController, :delete
    get "/profile", UserController, :profile
  end

  # Other scopes may use custom stacks.
  # scope "/api", Pong do
  #   pipe_through :api
  # end
end

web/controllers/session_controller.ex
defmodule Pong.SessionController do
  use Pong.Web, :controller

  alias Pong.User

  def new(conn, _) do
    changeset = User.changeset(%User{})
    render conn, "new.html", changeset: changeset
  end

  def create(conn, %{"user" => session}) do
    changeset = User.changeset %User{}, session
    if user = User.authenticate?(changeset) do
      conn
        |> put_session(:user_id, user.id)
        |> redirect(to: game_path(conn, :index))
    end
    render conn, "new.html", changeset: changeset
  end

  def delete(conn, _) do
    conn
      |> put_session(:user_id, nil)
      |> redirect(to: session_path(conn, :new))
  end

end

web/views/session_view.ex
defmodule Pong.SessionView do
  use Pong.Web, :view
end

web/templates/session/new.html.eex
<div class="col-sm-4 col-sm-offset-4">
  <h2>Log In</h2>
<%= form_for @changeset, session_path(@conn, :create), fn f-> %>
  <div class="form-group">
    <label>Email</label>
    <br />
    <%= text_input(f, :email, class: "form-control") %>
  </div>
  <div class="form-group">
    <label>Password</label>
    <br />
    <%= password_input(f, :password, class: "form-control") %>
  </div>
  <div class="actions">
    <%= submit "Log in", class: "btn btn-default" %>
    <%= link "Sign up", to: user_path(@conn, :new) %>
  </div>
<% end %>
</div>